### ISSUE TITLE
 Error is ../ViewController.swift:10:8: Cannot load underlying module for ‘AGNavigationBarShape' 

### ISSUE THREAD

**Issue by dimabiserov** [grifas/AGNavigationBarShape#2]
I do everything according to instructions, but when I try to import, it is such a mistake. I have the latest mac os and xcode

**Comment by grifas** [comment]
Hi, 

Which branch did you use to install the pod ? 

I recommend to use `pod "AGNavigationBarShape"` in your Podfile.

**Comment by dimabiserov** [comment]
hello, Yes, I tried and true, and has been used to account for Swift 3, and so and so error :(

**Comment by grifas** [comment]
Ok so, try:
- ChooseProduct | Clean then Product | Build
- Shutting down Xcode and reopening the workspace

**Comment by hell4opt** [comment]
don't work any way :( screens: http://imgur.com/a/PhB7w

**Comment by dimabiserov** [comment]
"Choose Product(on upside toolbar) | Clean then Product | Build" - it work, big thx!
