### ISSUE TITLE
title did not change

### ISSUE THREAD

**Issue by dimabiserov** [grifas/AGNavigationBarShape#3]
How can i change the title? 
navigationController?.navigationBar.titleTextAttributes = [NSForegroundColorAttributeName: UIColor.white, NSFontAttributeName: UIFont(name: "Verdana", size: 13)!]
        self.navigationItem.title = "Секреты"

this don't work
ant text from story board don't work too :(

**Comment by grifas** [comment]
I tried your code in the viewDidLoad of my example and it works.
